### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#257]
Idk if I broke something, but I cannot login anymore. I cleaned the database, tried an incognito browser with the login bypass, but somehow I always get either of those two errors back. Tests run fine though. (Currently working on branch for #219 )
```
ft_transcendence-backend-1   | [Nest] 47  - 10/25/2022, 11:48:37 AM   ERROR [ExceptionsHandler] Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
ft_transcendence-backend-1   | TokenError: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
ft_transcendence-backend-1   |     at /app/node_modules/passport-oauth2/lib/strategy.js:177:45
ft_transcendence-backend-1   |     at /app/node_modules/oauth/lib/oauth2.js:191:18
ft_transcendence-backend-1   |     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
ft_transcendence-backend-1   |     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
ft_transcendence-backend-1   |     at IncomingMessage.emit (node:events:525:35)
ft_transcendence-backend-1   |     at endReadableNT (node:internal/streams/readable:1359:12)
ft_transcendence-backend-1   |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

```
ft_transcendence-backend-1   | [Nest] 47  - 10/25/2022, 11:55:59 AM   ERROR [ExceptionsHandler] Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
ft_transcendence-backend-1   | TokenError: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
ft_transcendence-backend-1   |     at /app/node_modules/passport-oauth2/lib/strategy.js:177:45
ft_transcendence-backend-1   |     at /app/node_modules/oauth/lib/oauth2.js:191:18
ft_transcendence-backend-1   |     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
ft_transcendence-backend-1   |     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
ft_transcendence-backend-1   |     at IncomingMessage.emit (node:events:525:35)
ft_transcendence-backend-1   |     at endReadableNT (node:internal/streams/readable:1359:12)
ft_transcendence-backend-1   |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by GQDeltex** [comment]
Intra secrets renew themselves after a certain amount of time.  The Intra42Stategy error is gone now. I can login with intra. I still get an error if I try to login via the bypass:
```
ft_transcendence-backend-1   | [Nest] 47  - 10/25/2022, 12:15:51 PM   ERROR [ExceptionsHandler] The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
ft_transcendence-backend-1   | TokenError: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
ft_transcendence-backend-1   |     at Intra42Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
ft_transcendence-backend-1   |     at /app/node_modules/passport-oauth2/lib/strategy.js:177:45
ft_transcendence-backend-1   |     at /app/node_modules/oauth/lib/oauth2.js:191:18
ft_transcendence-backend-1   |     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
ft_transcendence-backend-1   |     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
ft_transcendence-backend-1   |     at IncomingMessage.emit (node:events:525:35)
ft_transcendence-backend-1   |     at endReadableNT (node:internal/streams/readable:1359:12)
ft_transcendence-backend-1   |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by GQDeltex** [comment]
My bad...
I forgot to update my `.env` file to include the bypass secret.
Well, closing this now 😆
